// Generated by https://quicktype.io

export interface CreateUserResponse {
	_id: string
	name: string
	password: string
	email: string
	token: string
	isconfirm: boolean
	createdAt: string
	updatedAt: string
	__v: number
}
